### ISSUE TITLE
Get pins by searcharea doesn't work

### ISSUE THREAD

**Issue by james-woo** [fridayideas/daytomatoserver#13]
http://localhost:8080/api/pins?searcharea=0,0,50,-50

Returns all pins no matter which search area you put

Need this fixed for client stuff.

**Comment by ToucheSir** [comment]
I don't seem to be getting this behaviour on either prod or the latest master (just an empty collection, as expected).

**Comment by james-woo** [comment]
Ah you're totally right

**Comment by james-woo** [comment]
Actually, it is not really working

**Comment by james-woo** [comment]
Discovered the issue, its not parsing floats

**Comment by ToucheSir** [comment]
will implement float support server side.
