### ISSUE TITLE
Yelp Crawler

### ISSUE THREAD

**Issue by alixvoor** [fridayideas/daytomatoserver#2]
- get initial data from Yelp using their api
- can be in any language
- get information depending on our schemas

**Comment by james-woo** [comment]
This is the Database Schema we would like to follow
// PINS
{
  "_id": <ObjectId>
  "rating": <string>,
  "pinType": <int>,
  "name": <string>,
  "description": <string>,
  "likes" : <int>,
  "duration": <long>,
  "coordinate": {
    "latitude": <double>,
    "longitude": <double>
  },
  "linkedAccount": <ObjectId>, 
  "reviews": [{"linkedAccount":<ObjectId>,"text":<string>,"createDate":<Date>}...]
}

//REVIEWS
{
  "_id": <ObjectId>
  "linkedPin": <ObjectId>,
  "linkedAccount": <ObjectId>, 
  "text": <string>
  "linkedAccount": <ObjectId>,
  "reviews": [ {
        "linkedAccount": <ObjectId>,
        "text": <string>,
        "date": <DateTime>
        },
        {
        "linkedAccount": <ObjectId>,
        "text": <string>,
        "date": <DateTime>
        } ...
      ]
}
