### ISSUE TITLE
Need GET pins to return likedBy and dislikedBy

### ISSUE THREAD

**Issue by james-woo** [fridayideas/daytomatoserver#30]
Currently it is not being returned, can we have it so it returns an empty list or a list of accounts?

Would need to change the get request for all pins and the get pins by id

**Comment by ToucheSir** [comment]
Is there a particular reason we need to return a list of accounts liking or disliking for any particular pin? The duplicate like validation is already performed server-side, and giving back a list of accounts wholesale to any user seems like a bit of a privacy issue.
