### ISSUE TITLE
Code Style and Linting?

### ISSUE THREAD

**Issue by ToucheSir** [fridayideas/daytomatoserver#4]
This might be complete yak shaving, but would there be interest in adding some form of code style or code linting check to this project? It might help somewhat with keeping changes consistent if we don't have to worry about inconsistent formatting across everyone's editors.

**Comment by ToucheSir** [comment]
For some popular examples that we could use and/or adapt, see the [airbnb](https://github.com/airbnb/javascript), [google](https://google.github.io/styleguide/javascriptguide.xml) and "[standard](https://github.com/feross/standard)" style guides.

**Comment by james-woo** [comment]
Do it! Create a pull request 👍

**Comment by ToucheSir** [comment]
closed via #5 .
